// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"


import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)

// import { NotificationsController } from "./notifications_controller"
// application.register("notifications", NotificationsController)

// Import SweetAlert2
import Swal from "sweetalert2";
application.register("confirmation", Swal);

application.register("select_option_slim");

application.register("dropdown", DropdownController)

application.register("copiedtext");
application.register("generate-password");
application.register("employee");